# Numpy

Documentation - https://numpy.org/doc/

At the core of the NumPy package, is the `ndarray` object. Numpy provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays

There are several important differences between NumPy arrays and the standard Python sequences:

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). __Changing the size of an ndarray will create a new array and delete the original.__

* __The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.__ The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

NumPy’s array class is called `ndarray`. In NumPy, dimensions are called `axes`.

In [1]:
import numpy as np
np.version.version

'1.19.1'

## Array Creation

### Create an array from a regular Python list or tuple using the array function

In [2]:


a_tuple = 1,2,3
a_list = [[ 0,  1,  2,  3,  4], [ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]]

a = np.array(a_tuple)

# array method transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array(a_list)

#  type of the array can also be explicitly specified at creation time
c = np.array(a_list, dtype=float)

print('a:\n', a)
print('b:\n', b)
print('c:\n', c)

print('\nType of elements: a = {}, b = {}, c = {}'.format(a.dtype, b.dtype, c.dtype))

a:
 [1 2 3]
b:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
c:
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]

Type of elements: a = int32, b = int32, c = float64


### Intitializing arrays with 0s, 1s or random values

In [3]:
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 2), dtype=np.int16)  
empty_array = np.empty((2, 2))

print('zeros_array:\n', zeros_array)
print('ones_array:\n', ones_array)
print('empty_array:\n', empty_array)

zeros_array:
 [[0. 0.]
 [0. 0.]]
ones_array:
 [[1 1]
 [1 1]]
empty_array:
 [[1.30434116e-311 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


### Creating arrays using range

In [4]:
# NumPy provides the arange function which is analogous to the Python built-in range, but returns an array
arange_array = np.arange(10, 30, 5)
arange_array

array([10, 15, 20, 25])

## Array Properties

In [36]:
b = np.array([[[1, 2]], [[2, 3]], [[3, 4]]])
print(b)

# dimensionality refers to the number of axes needed to index an array
print('Number of axes (dimensions) = ', b.ndim)
print('Shape (tuple of integers indicating the size of the array in each dimension) = ', b.shape)
print('Size (total number of elements in the array) = ', b.size)
print('Type of the elements in the array = ', b.dtype)
print('Size in bytes of each element of the array = ', b.itemsize)
print('The buffer containing the actual elements of the array = ', b.data)

[[[1 2]]

 [[2 3]]

 [[3 4]]]
Number of axes (dimensions) =  3
Shape (tuple of integers indicating the size of the array in each dimension) =  (3, 1, 2)
Size (total number of elements in the array) =  6
Type of the elements in the array =  int32
Size in bytes of each element of the array =  4
The buffer containing the actual elements of the array =  <memory at 0x00000266C91967C0>


## Array Operations

* Arithmetic operators on arrays apply elementwise. 
* A new array is created and filled with the result.

### Equality and basic arithmetic operations

In [6]:
a = np.ones((2,2))
b = np.ones((2,2))

display(a + b)
display(a < 35)

array([[2., 2.],
       [2., 2.]])

array([[ True,  True],
       [ True,  True]])

### Unary Operations

In [7]:
# many are implemented as methods of the ndarray class

a = np.ones((2,2)) * 4
display(a)

# By default, these operations apply to the array as though it were a list of numbers, regardless of its shape
display(a.sum())

# by specifying the axis parameter you can apply an operation along the specified axis of an array
a.sum(axis=1) # sum of each row

# NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.
display(np.sqrt(a))

array([[4., 4.],
       [4., 4.]])

16.0

array([[2., 2.],
       [2., 2.]])

### Elementwise and Matrix product

In [8]:
a = np.ones((2,2))
b = np.ones((2,2))

display(a * (a + b))                 # elementwise product
display(a @ b)                       # matrix product
display(a.dot(b))                    # matrix product

array([[2., 2.],
       [2., 2.]])

array([[2., 2.],
       [2., 2.]])

array([[2., 2.],
       [2., 2.]])

### In place modifications

In [9]:
a = np.ones((2,2))

a += 3 # new array is not created
display(a)

a += a # new array is not created
display(a)

array([[4., 4.],
       [4., 4.]])

array([[8., 8.],
       [8., 8.]])

### Indexing, Slicing and Iterating
https://numpy.org/doc/stable/user/quickstart.html#indexing-slicing-and-iterating

In [10]:
a = np.arange(0,10,1)
print('a = {}\n'.format(a))

print(a[0])
print(a[0:])  # 0 is inclusive
print(a[:9])  # 9 is exclusive
print(a[0:9]) # 0 is inclusive, 9 is exclusive
print(a[0:9:2])  # from start to position 9, exclusive, get every 2nd element
print(a[ : :-1]) # reverse

a_list = []
# iterate over ndarray
for i in a:
    a_list.append(i)
print('a_list = ', a_list)

a = [0 1 2 3 4 5 6 7 8 9]

0
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
a_list =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Shape Manipulation
https://numpy.org/doc/stable/user/quickstart.html#shape-manipulation

In [49]:
a = np.array([[3., 7., 3., 4.],
              [1., 4., 2., 2.],
              [7., 2., 4., 9.]])

print('size = ', a.size)
print('shape = ', a.shape)

print(a.ravel()) # returns the array, flattened
print(a.reshape(6,2))  # returns the array with a modified shape

# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated
print(a.reshape(3,2,-1).shape)

size =  12
shape =  (3, 4)
[3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]
[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]
 [7. 2.]
 [4. 9.]]
(3, 2, 2)


### Stacking arrays together
https://numpy.org/doc/stable/user/quickstart.html#stacking-together-different-arrays

In [53]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a)
print(b)

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Splitting one array into several smaller ones

Using [hsplit](https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html#numpy.hsplit), you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur.

[vsplit](https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html#numpy.vsplit) splits along the vertical axis, and [array_split](https://numpy.org/doc/stable/reference/generated/numpy.array_split.html#numpy.array_split) allows one to specify along which axis to split

In [85]:
from collections import deque

a = np.arange(1, 10, 1)
print('a = ', a)

deque(map(print, np.hsplit(a,3)))

a =  [1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6]
[7 8 9]


deque([None, None, None])

## Upcasting

When operating with arrays of different types, the type of the resulting array corresponds to the more __general__ or __precise__ one (a behavior known as upcasting).

In [12]:
# upcasting - precise

a = np.ones(2, dtype = np.int32)
b = np.ones(2, dtype = np.int64)

(a+b).dtype.name

'int64'

In [13]:
# upcasting - general

a = np.ones(2, dtype = np.int32)
b = np.ones(2, dtype = np.float)

(a+b).dtype.name

'float64'