# Numpy

Documentation - https://numpy.org/doc/

At the core of the NumPy package, is the `ndarray` object. Numpy provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays

There are several important differences between NumPy arrays and the standard Python sequences:

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). __Changing the size of an ndarray will create a new array and delete the original.__

* __The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.__ The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

NumPy’s array class is called `ndarray`. In NumPy, dimensions are called `axes`.

In [1]:
import numpy as np
np.version.version

'1.19.1'

### Array Creation

In [2]:
# Create an array from a regular Python list or tuple using the array function

a_tuple = 1,2,3
a_list = [[ 0,  1,  2,  3,  4], [ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]]

a = np.array(a_tuple)

# array method transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array(a_list)

#  type of the array can also be explicitly specified at creation time
c = np.array(a_list, dtype=float)

print('a:\n', a)
print('b:\n', b)
print('c:\n', c)

print('\nType of elements: a = {}, b = {}, c = {}'.format(a.dtype, b.dtype, c.dtype))

a:
 [1 2 3]
b:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
c:
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]

Type of elements: a = int32, b = int32, c = float64


In [3]:
# Intitializing arrays with 0s, 1s or random values

zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 2), dtype=np.int16)  
empty_array = np.empty((2, 2))

print('zeros_array:\n', zeros_array)
print('ones_array:\n', ones_array)
print('empty_array:\n', empty_array)

zeros_array:
 [[0. 0.]
 [0. 0.]]
ones_array:
 [[1 1]
 [1 1]]
empty_array:
 [[1.13952002e-311 5.73709992e+174]
 [1.42245340e+160 1.53459865e-075]]


In [7]:
# Creating arrays using range

# NumPy provides the arange function which is analogous to the Python built-in range, but returns an array
arange_array = np.arange(10, 30, 5)
arange_array

array([10, 15, 20, 25])

### Array Properties

In [5]:
print('Number of axes (dimensions) = ', b.ndim)
print('Shape (tuple of integers indicating the size of the array in each dimension) = ', b.shape)
print('Size (total number of elements of the array) = ', b.size)
print('Type of the elements in the array = ', b.dtype)
print('Size in bytes of each element of the array = ', b.itemsize)
print('The buffer containing the actual elements of the array = ', b.data)

Number of axes (dimensions) =  2
Shape (tuple of integers indicating the size of the array in each dimension) =  (3, 5)
Size (total number of elements of the array) =  15
Type of the elements in the array =  int32
Size in bytes of each element of the array =  4
The buffer containing the actual elements of the array =  <memory at 0x000002191B7F2D40>


### Array Operations

* Arithmetic operators on arrays apply elementwise. 
* A new array is created and filled with the result.

In [15]:
a = np.ones((2,2))
b = np.ones((2,2))
display(a + b)

# equality operation
a < 35

array([[2., 2.],
       [2., 2.]])

array([[ True,  True],
       [ True,  True]])

In [19]:
# elementwise and matrix product

a = np.ones((2,2))
b = np.ones((2,2))

display(a * (a + b))                 # elementwise product
display(a @ b)                       # matrix product
display(a.dot(b))                    # matrix product

array([[2., 2.],
       [2., 2.]])

array([[2., 2.],
       [2., 2.]])

array([[2., 2.],
       [2., 2.]])

In [25]:
# in place modifications - new array is not created

a = np.ones((2,2))

a += 3
display(a)

a += a
display(a)

array([[4., 4.],
       [4., 4.]])

array([[8., 8.],
       [8., 8.]])